version: '3.8'

services:
  web:
    build: .
    container_name: nyankomu-web
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0

volumes:
  node_modules: 