services:
  web:
    build: .
    container_name: nyankomu-web
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - vite_cache:/app/node_modules/.vite
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped

volumes:
  node_modules:
  vite_cache:
